### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by costalonga** [liviaaloise/INF1350#3]
- [x] player
- [x] bullets
- [x] items
  - [x] + speed
  - [x] adicionar outras funcionalidades e randomizar 
- [x] Terminar tiros dos oponentes
  - [x] Remover da lista ao sair da fase
  - [x] Criar timer pra fazer blips atirarem com passar do tempo
- [x] Solucionar problemas de lag
  - [x] ajuste dos parâmetros de wait e speed de cada componente
  - [x] utilizar corrotina para timer dos tiros dos blips, ao invés de variável global
  - [x] utilizar corrotina para timer do gerador de items, ao invés de variável global
